server:
  port: 8080
spring:
  application:
    name: wechat
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.133.81:3306/wechat?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 2000
mybatis:    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.wechat.bean